raghavic1995/SMILES

force-app/main/default/flows/Web2case_Document_Request.flow-meta.xml

[DevOps Center] Merge WI-000231 to Training

---

force-app/main/default/objects/Case/fields/Your_market__c.field-meta.xml

[DevOps Center] Merge WI-000232 to Training

---

force-app/main/default/reportTypes/Related_SAPP_of_SA.reportType-meta.xml

[DevOps Center] Merge WI-000217 to UAT

---

force-app/main/default/aura/EditAccPlan/EditAccPlan.cmp
force-app/main/default/aura/EditAccPlan/EditAccPlan.cmp-meta.xml
force-app/main/default/aura/EditAccPlan/EditAccPlanController.js
force-app/main/default/flows/Mass_Update_New.flow-meta.xml
force-app/main/default/objects/Product2/fields/Material_Group_5__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/MaterialGroup5__c.field-meta.xml

[DevOps Center] Merge WI-000238 to Training

---

force-app/main/default/aura/EditAccPlan/EditAccPlan.cmp
force-app/main/default/aura/EditAccPlan/EditAccPlan.cmp-meta.xml
force-app/main/default/aura/EditAccPlan/EditAccPlanController.js
force-app/main/default/flows/Mass_Update_New.flow-meta.xml
force-app/main/default/objects/Product2/fields/Material_Group_5__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/MaterialGroup5__c.field-meta.xml

[DevOps Center] Merge WI-000238 to UAT

---

force-app/main/default/objects/Case/validationRules/Manufacturing_Plant_Mandatory.validationRule-meta.xml
force-app/main/default/objects/Sample__c/validationRules/Manufacturing_Plant_Mandatory.validationRule-meta.xml

[DevOps Center] Merge WI-000243 to Training

---

force-app/main/default/objects/Case/fields/Business_Performance_Manager__c.field-meta.xml
force-app/main/default/objects/Case/fields/Sales_Director__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Business_Performance_Manager__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Market_VP__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Sales_Director__c.field-meta.xml
force-app/main/default/objects/Sample__c/fields/Business_Performance_Manager__c.field-meta.xml
force-app/main/default/objects/Sample__c/fields/Market_VP__c.field-meta.xml
force-app/main/default/objects/Sample__c/fields/Sales_Director__c.field-meta.xml
force-app/main/default/objects/TechnicalAssistanceRequest__c/fields/Business_Performance_Manager__c.field-meta.xml
force-app/main/default/objects/TechnicalAssistanceRequest__c/fields/Market_VP__c.field-meta.xml
force-app/main/default/objects/TechnicalAssistanceRequest__c/fields/Sales_Director__c.field-meta.xml
force-app/main/default/objects/VisitReport__c/fields/Business_Performance_Manager__c.field-meta.xml
force-app/main/default/objects/VisitReport__c/fields/Market_VP__c.field-meta.xml
force-app/main/default/objects/VisitReport__c/fields/Sales_Director__c.field-meta.xml

[DevOps Center] Merge WI-000246 to Training

---

force-app/main/default/flows/Case_BS_Create_Update.flow-meta.xml
force-app/main/default/flows/Opportunity_BS_Create_Update.flow-meta.xml
force-app/main/default/flows/Sample_BS_Create_Update.flow-meta.xml
force-app/main/default/flows/TAR_BS_Create_Update.flow-meta.xml
force-app/main/default/flows/Visit_Report_BS_Create_Update.flow-meta.xml

[DevOps Center] Merge WI-000247 to Training

---

force-app/main/default/classes/AP01_CaseTriggerHandler.cls
force-app/main/default/classes/AP01_OpportunityTriggerHandler.cls
force-app/main/default/classes/AP01_OpportunityTriggerHandler.cls-meta.xml
force-app/main/default/classes/AP01_SampleTriggerHandler.cls
force-app/main/default/classes/AP01_TechAssistReqTriggerHandler.cls
force-app/main/default/classes/AP01_TechAssistReqTriggerHandler.cls-meta.xml
force-app/main/default/classes/AP01_VisitReportTriggerHandler.cls
force-app/main/default/classes/AP01_VisitReportTriggerHandler.cls-meta.xml

[DevOps Center] Merge WI-000251 to Training

---

force-app/main/default/objects/SalesAgreementProduct/fields/Condition_Type__c.field-meta.xml

[DevOps Center] Merge WI-000254 to Training

---

force-app/main/default/classes/AP01_AccountPlanTeamTriggerHandler.cls
force-app/main/default/classes/AP01_AccountPlanTeamhandlerTest.cls
force-app/main/default/classes/AP01_AccountPlanTriggerHandler.cls
force-app/main/default/classes/AP01_AccountPlanTriggerHandler.cls-meta.xml
force-app/main/default/classes/AP01_AccountPlanTriggerHandlerTest.cls
force-app/main/default/classes/AP01_AccountPlanTriggerHandlerTest.cls-meta.xml
force-app/main/default/classes/AP_ImerysStrategicPositioning.cls
force-app/main/default/classes/AP_ImerysStrategicPositioning.cls-meta.xml
force-app/main/default/classes/AP_ImerysStrategicPositioningTest.cls
force-app/main/default/classes/AP_ImerysStrategicPositioningTest.cls-meta.xml
force-app/main/default/classes/AccountPlanStageTest.cls
force-app/main/default/classes/AccountPlanStages.cls
force-app/main/default/classes/AccountPlanStages.cls-meta.xml
force-app/main/default/classes/AccountsTableController.cls
force-app/main/default/classes/AccountsTableController.cls-meta.xml
force-app/main/default/classes/AccountsTableControllerTest.cls
force-app/main/default/classes/AccountsTableControllerTest.cls-meta.xml
force-app/main/default/classes/SOW.cls
force-app/main/default/classes/ShareOfWallet.cls
force-app/main/default/classes/ShareOfWallet.cls-meta.xml
force-app/main/default/classes/ShareOfWalletTest.cls
force-app/main/default/classes/ShareOfWalletTest.cls-meta.xml

[DevOps Center] Merge WI-000241 to UAT

---

force-app/main/default/flows/Mass_Update_New.flow-meta.xml

[DevOps Center] Merge WI-000258 to Training

---

force-app/main/default/flows/Mass_Update_New.flow-meta.xml

[DevOps Center] Merge WI-000259 to Training

---

force-app/main/default/objects/Account/fields/Market_Segmentation__c.field-meta.xml
force-app/main/default/objects/Capacity__c/fields/MarketSegmentation__c.field-meta.xml
force-app/main/default/objects/Case/fields/MarketSegmentationNew__c.field-meta.xml
force-app/main/default/objects/Consumption__c/fields/MarketSegmentation__c.field-meta.xml
force-app/main/default/objects/M_A_Target__c/fields/Market_Segmentation__c.field-meta.xml
force-app/main/default/objects/Offer__c/fields/MarketSegmentationNew__c.field-meta.xml
force-app/main/default/objects/Opportunity/fields/Market_Segmentation_new__c.field-meta.xml
force-app/main/default/objects/Project__c/fields/MarketSegmentationNew__c.field-meta.xml
force-app/main/default/objects/Relationship__c/fields/MarketSegmentation__c.field-meta.xml
force-app/main/default/objects/Relationship__c/fields/Market_Segmentation_Secondary__c.field-meta.xml
force-app/main/default/objects/Sample__c/fields/MarketSegmentation__c.field-meta.xml
force-app/main/default/objects/TechnicalAssistanceRequest__c/fields/Market_Segmentation__c.field-meta.xml
force-app/main/default/objects/VisitReport__c/fields/MarketSegmentation_Secondary__c.field-meta.xml
force-app/main/default/objects/VisitReport__c/fields/MarketSegmentation__c.field-meta.xml

[DevOps Center] Merge WI-000261 to Training

---

force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_Chinese_1680252755716.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_Chinese_1680252755716.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_English_1678869636325.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_English_1678869636325.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_French_1678870144946.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_French_1678870144946.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_German_1678862966605.email

[DevOps Center] Merge WI-000269 to Training

---

force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_Chinese_1680252755716.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_Chinese_1680252755716.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_English_1678869636325.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_English_1678869636325.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_French_1678870144946.email
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_French_1678870144946.email-meta.xml
force-app/main/default/email/unfiled$public/Embed_a_Survey_Link_German_1678862966605.email

[DevOps Center] Merge WI-000269 to UAT

---

force-app/main/default/objects/Contact/fields/Tech_Account_Name__c.field-meta.xml

[DevOps Center] Merge WI-000272 to Training

---

force-app/main/default/objects/Contact/fields/Tech_Account_Name__c.field-meta.xml

[DevOps Center] Merge WI-000272 to UAT

---

force-app/main/default/flows/Email_Alert_notification_on_Negative_feedback.flow-meta.xml
force-app/main/default/flows/Send_survey_invitation_to_case_contact.flow-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000271 to Training

---

force-app/main/default/flows/Email_Alert_notification_on_Negative_feedback.flow-meta.xml
force-app/main/default/flows/Send_survey_invitation_to_case_contact.flow-meta.xml
force-app/main/default/workflows/Case.workflow-meta.xml

[DevOps Center] Merge WI-000271 to UAT

---

force-app/main/default/layouts/Quote-Quote After Creation.layout-meta.xml
force-app/main/default/objects/Quote/fields/DateClosed__c.field-meta.xml
force-app/main/default/objects/Quote/fields/End_Of_Validity__c.field-meta.xml
force-app/main/default/objects/Quote/fields/ReasonForClosing__c.field-meta.xml
force-app/main/default/objects/Quote/fields/Start_of_Validity__c.field-meta.xml

[DevOps Center] Merge WI-000274 to Training

---

force-app/main/default/flows/SAP_Toast_Message.flow-meta.xml

[DevOps Center] Merge WI-000276 to Training

---

force-app/main/default/layouts/QuoteLineItem-Quote Line Item Layout.layout-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Dispatch_Site__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Drayage_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/End_Date_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Energy_surcharge_per_uom_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Freight_surcharge_per_uom_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Fuel_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/ICMS__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Inflation_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/New_Product_Unit_price_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/PIS_COFINS__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Packaging_Price_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Product_Price_Per_Unit_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Sales_Price_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Start_Date_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Steric_Acid_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Surcharge__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Surcharges_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Territory__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Total_Price_exc_surcharge_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Total_Price_inc_Surcharge_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Transport_price_per_container_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Transport_price_per_unit_PM_A__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Transport_price_unit_base_PM_A__c.field-meta.xml

[DevOps Center] Merge WI-000277 to Training

---

force-app/main/default/flows/Mass_Update_New.flow-meta.xml

[DevOps Center] Merge WI-000279 to Training

---

force-app/main/default/objects/Case/validationRules/CSE_VR59_Credit_Note_ERP_Rebill_Number.validationRule-meta.xml

[DevOps Center] Merge WI-000230 to UAT

---

force-app/main/default/objects/Imerys_Site__c/fields/Standard_Terms_Conditions_of_Sales_L__c.field-meta.xml
force-app/main/default/objects/Quote/fields/Standard_Terms_Conditions_of_Sales__c.field-meta.xml

[DevOps Center] Merge WI-000285 to Training

---

force-app/main/default/objects/Imerys_Site__c/fields/Standard_Terms_Conditions_of_Sales_L__c.field-meta.xml
force-app/main/default/objects/Quote/fields/Standard_Terms_Conditions_of_Sales__c.field-meta.xml

[DevOps Center] Merge WI-000285 to UAT

---

force-app/main/default/objects/Case/validationRules/CSE_VR59_Credit_Note_ERP_Rebill_Number.validationRule-meta.xml
force-app/main/default/objects/Imerys_Site__c/fields/Standard_Terms_Conditions_of_Sales_L__c.field-meta.xml
force-app/main/default/objects/Quote/fields/Standard_Terms_Conditions_of_Sales__c.field-meta.xml

[DevOps Center] Merge UAT to Production

---

force-app/main/default/objects/Quote/fields/Product_Percent_Completion__c.field-meta.xml
force-app/main/default/objects/Quote/validationRules/QUO_VR13_QuoteLifecycle.validationRule-meta.xml
force-app/main/default/objects/Quote/validationRules/QUO_VR14_QuotePendingApproval.validationRule-meta.xml
force-app/main/default/pathAssistants/Quote_After_Creation.pathAssistant-meta.xml
force-app/main/default/quickActions/Quote.FinalizeStageQuoteFinalization.quickAction-meta.xml

[DevOps Center] Merge WI-000286 to Training

---

force-app/main/default/objects/SalesAgreementProduct/fields/Energy_Surcharge_Reports__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/KMEIN_Condition_Unit__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/Old_Full_Delivered_Price_Number__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/Previous_Product_Unit_Price_number__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/Total_transport_price_opera__c.field-meta.xml
force-app/main/default/objects/SalesAgreementProduct/fields/Unit__c.field-meta.xml
force-app/main/default/objects/Sales_Agreement_Product_Price__c/fields/KMEIN_Condition_Unit__c.field-meta.xml
force-app/main/default/objects/Sales_Agreement_Product_Price__c/fields/New_Freight_UM__c.field-meta.xml

[DevOps Center] Merge WI-000289 to Training

---

force-app/main/default/reportTypes/JDE_Report_P2Q.reportType-meta.xml
force-app/main/default/reports/unfiled$public/New_JDE_Report_P2Q_Report_Ghj.report-meta.xml

[DevOps Center] Merge WI-000290 to Training

---

force-app/main/default/objects/Relationship__c/fields/Key_Account_Manager_Workday_ID__c.field-meta.xml

[DevOps Center] Merge WI-000309 to Training

---

force-app/main/default/objects/Relationship__c/fields/Key_Account_Manager_Workday_ID__c.field-meta.xml

[DevOps Center] Merge WI-000309 to UAT

---

force-app/main/default/objects/Lead/validationRules/LEA_VR03_CityMandatoryForConverting.validationRule-meta.xml
force-app/main/default/objects/Lead/validationRules/LEA_VR05_JobDepartMandatoryForConverting.validationRule-meta.xml
force-app/main/default/objects/Lead/validationRules/LEA_VR06_MarketL1MandatoryForConverting.validationRule-meta.xml

[DevOps Center] Merge WI-000310 to Training

---

force-app/main/default/flows/Accept_User_Feedback.flow-meta.xml
force-app/main/default/flows/Feedback_Form.flow-meta.xml
force-app/main/default/flows/Update_Feedback_Status.flow-meta.xml
force-app/main/default/layouts/User_Feedback__c-User Feedback Layout.layout-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Additional_User_Comments__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Comments__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Owner__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Parent_Record__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Rating__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/fields/Status__c.field-meta.xml
force-app/main/default/objects/User_Feedback__c/listViews/All.listView-meta.xml

[DevOps Center] Merge WI-000307 to Training

---

force-app/main/default/objects/QuoteLineItem/fields/Drayage_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Export_Container_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Fuel_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/ICMS__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/PIS_COFINS__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Steric_Acid_Surcharge_per_uom__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Surcharges1__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/fields/Total_Price_inc_surcharge__c.field-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_Drayge_Surcharge_for_PMA_Users.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_Fuel_Surcharge_for_PMA_Users.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_ICMS_for_PMA_Users.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_InflationSurcharge_for_PMAUsers.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_PIS_COFINS_for_PMA_Users.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_Streic_Surcharge_for_PMA_Users.validationRule-meta.xml
force-app/main/default/objects/QuoteLineItem/validationRules/Restrict_export_Surcharge_for_PMA_Users.validationRule-meta.xml

[DevOps Center] Merge WI-000313 to Training

---

force-app/main/default/flows/SAP_CreateCase.flow-meta.xml
force-app/main/default/objects/GatekeeperAssignment__c/fields/Price_Update_Queue__c.field-meta.xml

[DevOps Center] Merge WI-000315 to Training

---

force-app/main/default/flows/Sales_agreement_team_Delete_Condition.flow-meta.xml
force-app/main/default/objects/Sales_Agreement_Product_Price__c/fields/Tech_SA__c.field-meta.xml

[DevOps Center] Merge WI-000301 to UAT

---

force-app/main/default/flows/Sales_Agreement_Share_to_all_SA_team_members.flow-meta.xml
force-app/main/default/flows/Sales_Agreement_Team.flow-meta.xml
force-app/main/default/flows/Sales_agreement_team_Delete_Condition.flow-meta.xml

[DevOps Center] Merge WI-000330 to Training

---

force-app/main/default/flows/Sales_Agreement_Share_to_all_SA_team_members.flow-meta.xml
force-app/main/default/flows/Sales_Agreement_Team.flow-meta.xml
force-app/main/default/flows/Sales_agreement_team_Delete_Condition.flow-meta.xml

[DevOps Center] Merge WI-000330 to UAT

---

force-app/main/default/flows/Update_Sales_Agreement_Team.flow-meta.xml

[DevOps Center] Merge WI-000331 to Training

---

force-app/main/default/flows/Update_Sales_Agreement_Team.flow-meta.xml

[DevOps Center] Merge WI-000331 to UAT
